---
- name: deploy nsx appliance
  vmware_deploy_ovf:
    hostname: "{{ nsx_ovf_vsphere_hostname }}"
    username: "{{ nsx_ovf_vsphere_username }}"
    password: "{{ nsx_ovf_vsphere_password }}"
    validate_certs: "{{ nsx_ovf_vsphere_validate_certs|default(omit) }}"
    allow_duplicates: "{{ nsx_ovf_allow_duplicates }}"
    datacenter: "{{ nsx_ovf_datacenter }}"
    cluster: "{{ nsx_ovf_cluster }}"
    datastore: "{{ nsx_ovf_datastore }}"
    deployment_option: "{{ nsx_ovf_deployment_option }}"
    disk_provisioning: "{{ nsx_ovf_disk_provisioning }}"
    fail_on_spec_warnings: "{{ nsx_ovf_fail_on_spec_warnings }}"
    folder: "{{ nsx_ovf_folder|default(omit) }}"
    name: "{{ nsx_ovf_vmname }}"
    networks: "{{ nsx_ovf_networks }}"
    ovf: "{{ nsx_ovf_path }}"
    power_on: "{{ nsx_ovf_power_on }}"
    properties:
      nsx_role: "{{ nsx_ovf_role|default(omit) }}"
      nsx_ip_0: "{{ nsx_ovf_ip_address }}"
      nsx_netmask_0: "{{ nsx_ovf_netmask }}"
      nsx_gateway_0: "{{ nsx_ovf_gateway }}"
      nsx_dns1_0: "{{ nsx_ovf_dns_servers|join(' ') }}"
      nsx_domain_0: "{{ nsx_ovf_domain }}"
      nsx_ntp_0: "{{ nsx_ovf_ntp_servers|join(' ') }}"
      nsx_isSSHEnabled: "{{ nsx_ovf_enable_ssh }}"
      nsx_allowSSHRootLogin: "{{ nsx_ovf_enable_root_ssh }}"
      nsx_passwd_0: "{{ nsx_ovf_password }}"
      nsx_cli_passwd_0: "{{ nsx_ovf_root_password }}"
      nsx_hostname: "{{ nsx_ovf_vmhostname }}"
    resource_pool: "{{ nsx_ovf_resource_pool|default(omit) }}"
    wait: "{{ nsx_ovf_wait }}"
    wait_for_ip_address: "{{ nsx_ovf_wait_for_ip_address }}"
